### ISSUE TITLE
Support for custom log levels

### ISSUE THREAD

**Issue by radiophysicist** [kiwicom/structlog-sentry#108]
Hi,

Some libraries (`uvicorn` in my case) use custom log levels registered via `logging.addLevelName()`.
I obtained crash with the following traceback due to such an loglevel in the event being sent to sentry:
```
--- Logging error ---

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/venv/lib/python3.9/site-packages/structlog/stdlib.py", line 963, in format
    ed = p(logger, meth_name, ed)
  File "/venv/lib/python3.9/site-packages/structlog_sentry/__init__.py", line 179, in __call__
    level = getattr(logging, event_dict["level"].upper())
AttributeError: module 'logging' has no attribute 'TRACE'
```
It seems that level names should be resolved to their values using `logging.getLevelName()` instead of just `getattr(logging, NAME)` to take into account custom log levels.

P.S.
I use the latest version of `structlog-sentry` (i.e.` 2.0.0`)

**Comment by radiophysicist** [comment]
Fix could be something like this: https://github.com/kiwicom/structlog-sentry/pull/109

**Comment by paveldedik** [comment]
Hi @radiophysicist
thank you very much, I'll check it soon

**Comment by paveldedik** [comment]
Fixed by https://github.com/kiwicom/structlog-sentry/pull/109
