### ISSUE TITLE
JSON not extracted to Sentry event

### ISSUE THREAD

**Issue by threewordphrase** [kiwicom/structlog-sentry#15]
I recently integrated django-structlog into my project, and my Sentry events started coming though as unique JSON strings which are impossible to group for resolution/ignoring:

![Screenshot from 2019-12-18 12-56-39](https://user-images.githubusercontent.com/1591971/71122765-2b179c00-2196-11ea-99a3-e292a86b983f.png)

I was under the impression this library would help me parse those `{'request_id':...` events. I've followed the setup instructions in this repo and `logger.error` messages are coming through correctly, like the `an_error_occurred` message in the middle of the list, which is great, but I would still like to fix the others.

Will this library do what I want? Should I look somewhere else?

**Comment by mrezzamoradi** [comment]
@threewordphrase  Can you include an example of the code you are using to log events?

**Comment by threewordphrase** [comment]
I've added SentryJsonProcessor which removes the events from sentry:
```python
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        SentryJsonProcessor(level=logging.ERROR, tag_keys="__all__"),
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.ExceptionPrettyPrinter(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    context_class=structlog.threadlocal.wrap_dict(dict),
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)
```

**Comment by yoshi-lyosha** [comment]
But in that case you are loosing breadcrumbs.

Better solution that I found for myself is to modify `LoggingIntegration` like:

```python
sentry_logging_integration = LoggingIntegration(event_level=None)
sentry_sdk.init(
    ...,
    integrations=[sentry_logging_integration],
)
```
