### ISSUE TITLE
migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x

### ISSUE THREAD

**Issue by mounirmesselmeni** [kiwicom/structlog-sentry#161]
/home/app/venv/lib/python3.12/site-packages/structlog_sentry/__init__.py:111: SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
  return self._hub or Hub.current

Sentry SDK version: 2.12.0
structlog-sentry version: 2.1.0

**Comment by paveldedik** [comment]
Should be fixed by https://github.com/kiwicom/structlog-sentry/commit/91c6dbe05c9565826e038d9b58d51f60eb4e7bf3

That is `structlog-sentry` version `2.2.0`. If there are any issues, please don't hesitate to open a new issue.
