### ISSUE TITLE
Log messages are sent twice when using processors.JSONRenderer

### ISSUE THREAD

**Issue by icamys** [kiwicom/structlog-sentry#3]
First of all I would like to thank you guys for this package. It's really nice.

In production environment I use `processors.JSONRenderer` to format logs properly for log storages like [elk-stack](https://www.elastic.co/elk-stack). Now I am trying to configure sentry in compound with structlog and your package. 

The problem is that the log messages are sent twice.

Here's the code:
```python

## config = dict(...)

if config.sentry.enabled:
    sentry_sdk.init(
        dsn=config.sentry.dsn,
        send_default_pii=True,
        attach_stacktrace="On",
    )

logging.basicConfig(format='%(message)s', stream=sys.stdout, level=config.level)

chain = [
    structlog.stdlib.add_log_level,
    SentryProcessor(level=logging.WARNING, active=config.sentry.enabled),
    structlog.processors.JSONRenderer(),
]

structlog.configure_once(
    processors=chain,
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)
```

Result screenshot:

![image](https://user-images.githubusercontent.com/6891299/58564118-0c22de00-8235-11e9-8243-d5f832ba36f5.png)

Any suggestions on how to workaround this?

**Comment by paveldedik** [comment]
For some reason I completely missed this issue, but it seems @mrezzamoradi fixed this in his PR which we hopefully merge during the week.

Thank you for reporting this.
